version: '3.0'
services:
  zookeeper:
    build: .
    image: zk1
#    container_name: zk1
    environment:
      - ZK_MODE=standalone
      - ZK_SERVER_NAME=zookeeper_zookeeper
      - ZK_SERVER_NUM=0
    ports:
      - 2181
      - 2888
      - 3888
#      - 2181:2181
#      - 2888:2888
#      - 3888:3888
    networks:
      - net_zookeeper

networks:
  net_zookeeper:
    driver: bridge
