version: '3.0'
services:
  zk-0:
    build: .
    image: hongchhe/zk
    container_name: zk-0
    environment:
      - ZK_MODE=replicated
      - ZK_SERVER_NAME=zk
      - ZK_SERVER_NUM=3
      - ZK_SERVER_ID=0
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - net_zookeeper

  zk-1:
    image: hongchhe/zk
    container_name: zk-1
    environment:
      - ZK_MODE=replicated
      - ZK_SERVER_NAME=zk
      - ZK_SERVER_NUM=3
      - ZK_SERVER_ID=1
    ports:
      - 2181
      - 2888
      - 3888
#      - 2181:2181
#      - 2888:2888
#      - 3888:3888
    networks:
      - net_zookeeper

  zk-2:
    image: hongchhe/zk
    container_name: zk-2
    environment:
      - ZK_MODE=replicated
      - ZK_SERVER_NAME=zk
      - ZK_SERVER_NUM=3
      - ZK_SERVER_ID=2
    ports:
      - 2181
      - 2888
      - 3888
#      - 2181:2181
#      - 2888:2888
#      - 3888:3888
    networks:
      - net_zookeeper

networks:
  net_zookeeper:
    driver: bridge
