version: '3.0'
services:
  zk1:
    build: .
    image: hongchhe/zk
    container_name: zk1
    volumes:
      - ./myvol:/myvol
    environment:
      - ZK_MODE=replicated
      - ZK_SERVER_NAME=zk
      - ZK_SERVER_NUM=3
      - ZK_SERVER_ID=1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - net_zookeeper

  zk2:
    image: hongchhe/zk
    container_name: zk2
    volumes:
      - ./myvol:/myvol
    environment:
      - ZK_MODE=replicated
      - ZK_SERVER_NAME=zk
      - ZK_SERVER_NUM=3
      - ZK_SERVER_ID=2
    ports:
      - 2181
      - 2888
      - 3888
#      - 2181:2181
#      - 2888:2888
#      - 3888:3888
    networks:
      - net_zookeeper

  zk3:
    image: hongchhe/zk
    container_name: zk3
    volumes:
      - ./myvol:/myvol
    environment:
      - ZK_MODE=replicated
      - ZK_SERVER_NAME=zk
      - ZK_SERVER_NUM=3
      - ZK_SERVER_ID=3
    ports:
      - 2181
      - 2888
      - 3888
#      - 2181:2181
#      - 2888:2888
#      - 3888:3888
    networks:
      - net_zookeeper

networks:
  net_zookeeper:
    driver: bridge
