From ubuntu:14.04
MAINTAINER Hongchuang <hehongchuang@hotmail.com>

# install openssh-server, openjdk and wget
RUN     apt-get update \
     && apt-get install -y openssh-server openjdk-7-jdk wget curl ssh rsync

# set environment variable
ENV     JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64 
